// Shared "About" content — used by both the main-menu modal and the in-game
// panel so the credits & Rialo badge stay identical everywhere.
import { paintRialoMark } from '../world/landmarks.js';

export const TEAM = [
  { name: 'Nxrskyaa', role: 'GAME DEVELOPER', x: 'https://x.com/nxrskyaa' },
  { name: 'Dikzzy', role: 'GAME TESTER & BUG HUNTER', x: 'https://x.com/diikzzyy__' },
  { name: 'Baster', role: 'TECHNICAL GAME DEVELOPER', x: 'https://x.com/Bas_Basterx' },
];

// inner HTML for an About card. `logoSrc` is the cleaned Semesta logo data-URL
// (menu) or empty (in-game panel, which shows a heading instead).
export function aboutInner(logoSrc) {
  const members = TEAM.map((m) => `
    <div class="member">
      <div class="who"><b>${m.name}</b><small>${m.role}</small></div>
      <a class="xmini" href="${m.x}" target="_blank" rel="noopener">𝕏 FOLLOW</a>
    </div>`).join('');
  return `
    ${logoSrc ? `<img class="mascot" src="${logoSrc}" alt="Semesta">` : ''}
    <h4>◆ ABOUT ANAVELA UNIVERSE ◆</h4>
    <p>A cozy voxel action RPG.<br>
    Every texture, sound and creature is generated by code —<br>no asset packs, just pixels and vibes.</p>
    <div class="crew">
      <div class="ct">— THE TEAM —</div>
      ${members}
    </div>
    <div class="rialo-badge">
      <canvas class="rlogo-about" width="44" height="44"></canvas>
      <span>BUILD FOR RIALO</span>
    </div>`;
}

// paint the little Rialo mark into any freshly-inserted `.rlogo-about` canvases
export function paintAboutRialo(root) {
  root.querySelectorAll('.rlogo-about').forEach((cv) => {
    paintRialoMark(cv.getContext('2d'), cv.width);
  });
}

// shared CSS for the Rialo badge row (both surfaces already style .crew etc.)
export const ABOUT_BADGE_CSS = `
  .rialo-badge { display: flex; align-items: center; justify-content: center; gap: 10px;
    margin-top: 14px; padding-top: 12px; border-top: 1px solid rgba(216,184,102,0.25);
    font-family: var(--font-display, monospace); font-size: 11px; letter-spacing: 3px; color: #e8e3d5; }
  .rialo-badge canvas { width: 26px; height: 26px; image-rendering: pixelated; border-radius: 5px;
    box-shadow: 0 0 0 1px rgba(232,227,213,0.4), 0 2px 8px rgba(0,0,0,0.4); }
`;
