// THE SEMESTA GUIDE.
//
// Everything the game knows how to teach, in one place, reachable from the main
// menu BEFORE you commit to a character — because the questions a new player has
// ("what is this?", "do I need a wallet?", "what am I supposed to do first?")
// all arrive before they press NEW ADVENTURE, not after.
//
// Shape follows the pattern that works for browser games with a lot of systems:
// a categorised sidebar down the left, long-form sections on the right, and
// callout lists for "do this first" / "leave this alone for now". Everything
// here is DATA — the renderer below builds both the sidebar and the body from
// SECTIONS, so a new topic is one entry, never two.
//
// House rules for the copy: say what the player does, name the key, and be
// honest. The GameFi chapter in particular states plainly that nothing is
// on-chain yet, because a guide that oversells is worse than no guide.

const S = (id, title, body) => ({ id, title, body });

/** A bullet list. */
const ul = (items) => `<ul>${items.map((i) => `<li>${i}</li>`).join('')}</ul>`;
/** A highlighted callout: `tone` is 'do' (green) or 'dont' (red). */
const call = (tone, title, items) =>
  `<div class="cal ${tone}"><h4>${title}</h4>${ul(items)}</div>`;
/** A two-column key/value table. */
const kv = (rows) =>
  `<table class="kv">${rows.map(([k, v]) => `<tr><th>${k}</th><td>${v}</td></tr>`).join('')}</table>`;

export const CATEGORIES = [
  {
    name: 'GETTING STARTED',
    sections: [
      S('intro', 'Introduction', `
        <p>Semesta is a browser action RPG. You explore a hand-built voxel world
        called <b>Anavela Universe</b>, fight the creatures that moved in when the
        lanterns went out, and slowly make the place liveable again — farming,
        fishing, cooking, crafting, and eventually building a house of your own.</p>
        <p>There is no wallet, no download and no sign-up you are forced into. Your
        progress saves to this browser automatically; signing in with Google is
        optional and only adds a cloud copy. Everything you see — every texture,
        every sound, every note of music — is generated by code as the game loads.
        Semesta ships no image or audio files at all.</p>
        ${kv([
          ['Genre', 'Action RPG, 2.5D voxel. Solo, or a shared world if you want one'],
          ['Session', 'Play for five minutes or five hours — it saves constantly'],
          ['Saves to', 'This browser, and the cloud if you sign in'],
          ['Costs', 'Nothing'],
        ])}
        <p>The title screen has <b>two doors</b>, deliberately not one. NEW
        ADVENTURE and CONTINUE build a private world that is yours alone.
        <b>🌐 PLAY ONLINE</b> joins a shared one — same map, one clock, other
        people walking around in it, and world chat. Having a server available
        should never push somebody into a world with strangers in it.</p>`),

      S('first', 'Your First Session', `
        <p>A new hero spawns in the middle of the temple plaza with a starting
        weapon and nothing else. The villagers around you are the tutorial: every
        one of them will either give you a job or sell you something.</p>
        ${call('do', 'Do these first', [
          'Walk up to a villager with a <b>!</b> over their head and press <b>F</b>. That is your first quest.',
          'Read the signboards on the plaza — <b>SHOP</b>, <b>FORGE</b> and <b>GACHA</b> each stand on their own avenue.',
          'Chop a birch tree and mine an ore boulder (walk up, press <b>F</b>, three hits each). Nearly every recipe wants those two.',
          'Open the bag with <b>I</b> and put a healing tonic on your hotbar.',
          'Follow the one-line hint under your quest tracker — it always names the next thing worth doing.',
        ])}
        ${call('dont', 'Leave these for later', [
          'Wandering far from the village before level 5 — monsters scale with distance as well as with you.',
          'Spending your first coins on the capsule machine. Buy a better weapon and a stack of tonics first.',
          'Anything with a spinning gold ring and a ★ on its nameplate. Those are elites and they hit like it.',
          'Worrying about your class. You do not have one yet and you will not until Lv10 — see <i>Classes & Skills</i>.',
        ])}
        <p class="note">Nothing you do in the first hour can be got wrong in a way
        that matters. Dying costs nothing permanent, attribute points are the only
        irreversible spend and they start small, and the one choice that truly
        cannot be undone — your class — is ten levels away and asks you twice.</p>`),

      S('controls', 'Controls', `
        <p>Everything is rebindable in spirit but fixed in practice — these are
        the keys the game teaches:</p>
        ${kv([
          ['Move', '<b>W A S D</b> / arrow keys — on touch, the left half of the screen is a floating stick'],
          ['Look', 'Drag with the mouse, or swipe the right half on touch'],
          ['Zoom', 'Mouse wheel, or pinch with two fingers'],
          ['Attack', '<b>Left click</b>, or the ⚔ button on touch'],
          ['Skills', '<b>1 – 3</b>'],
          ['Interact', '<b>F</b> for the main action, <b>R</b> for the second one'],
          ['Jump', '<b>Space</b>'],
          ['Roll', '<b>Shift</b> or <b>right click</b> — in deep water it becomes a dive'],
          ['Bag', '<b>I</b>'],
          ['Skills panel', '<b>K</b>'],
          ['Wardrobe', '<b>O</b>'],
          ['World map', '<b>N</b> — tap the map to drop a waypoint'],
          ['Daily', '<b>J</b>'],
          ['Character stats', '<b>Z</b> — three points a level, no respec'],
          ['Life skills', '<b>L</b> — fishing, farming and cooking'],
          ['Teleport home', '<b>T</b> — 1.6s channel, 20s cooldown'],
          ['Teleport to basecamp', '<b>Y</b> — same channel, shared cooldown'],
          ['Mount', '<b>M</b>'],
          ['Chat', '<b>Enter</b> in a shared world, or the 💬 button'],
          ['AFK fishing', '<b>G</b>'],
          ['Auto-battle', '<b>B</b> — unlocks at Lv10'],
          ['Tilt the camera', '<b>↑ ↓</b>, or drag vertically on touch'],
          ['Menu', '<b>☰</b> button, or <b>Esc</b> to close anything'],
        ])}
        <p class="note">The <b>F</b> and <b>R</b> split matters: standing on a farm
        plot next to a villager, <b>F</b> plants and <b>R</b> talks. The prompt at
        the bottom of the screen always names both.</p>`),
    ],
  },

  {
    name: 'THE WORLD',
    sections: [
      S('basecamp', 'Anavela Universe', `
        <p>The basecamp is a paved temple plaza laid out on four avenues running
        out from the centre at 45°. Everything is placed on those axes, so once
        you know the shape you can find anything without the map.</p>
        ${ul([
          '<b>Shrine fountain</b> — closes the fourth avenue. The heart of the town.',
          '<b>SHOP</b> — Pip\'s stall. Seeds, food, tonics, watercraft keys.',
          '<b>FORGE</b> — the anvil. Upgrade a weapon +1 to +9 with forge stones.',
          '<b>GACHA</b> — Master NXR\'s capsule machine. Cosmetics, exclusive pets and mounts.',
          '<b>FARM</b> — eight plots just outside the plaza. Two are free.',
          '<b>Huts</b> — an outer ring between the avenues, where the villagers live.',
          '<b>Rialo monument</b> — the banner by the plaza edge.',
        ])}
        <p>The whole village is a <b>safe zone</b>: nothing spawns inside it, and
        anything chasing you gives up at the boundary.</p>`),

      S('wilds', 'The Wilds', `
        <p>Outside the village the land opens into meadow, forest and rock. Enemy
        level rises with distance from the village <i>and</i> with your own level,
        so the wilds never stop being worth walking into.</p>
        ${ul([
          '<b>Rest camps</b> — six of them, each with a campfire, a tent and a Ranger fox who heals you to full. Safe zones.',
          '<b>Gatherables</b> — pale birch trees give hardwood, glowing ore boulders give iron and forge stones. Both respawn.',
          '<b>Treasure chests</b> — sparkle from a distance. Loot one and another appears elsewhere.',
          '<b>Elites</b> — 8% of monsters above level 1. Bigger, gold ring, ★ on the nameplate, far better drops.',
          '<b>World bosses</b> — one spawns every three minutes, always well away from town. Watch the gold marker on the minimap.',
        ])}`),

      S('winter', 'The Winter Reach', `
        <p>The north-west corner of the map is under snow — frosted white-blue
        trees, snowfall that fades in as you cross the treeline, and two species
        you will not meet anywhere else.</p>
        ${ul([
          '<b>Frostling</b> — a crystal fox that throws icy orbs. Half of all winter spawns.',
          '<b>Sparkit</b> — a static squirrel, fast and twitchy.',
        ])}`),

      S('sea', 'The Ocean & Islands', `
        <p>The south-east third of the map is open sea with <b>nine islands</b> in
        it. Every water tile is enterable: wade out and you start swimming about
        two units from the sand. The longest straight run over open water is
        around ten seconds flat out on the Donut Boat.</p>
        ${ul([
          '<b>Swimming</b> costs stamina and does not regenerate it — roughly eighteen seconds of open water. Run out and you are towed to the nearest beach and put down on it, not drowned.',
          '<b>Diving</b> — the dodge-roll becomes a dive once you are afloat.',
          '<b>Watercraft</b> — the marina on the coast nearest the village moors your boats. See <i>Boats & Donut Boat</i>.',
          '<b>Islands</b> — each has its own silhouette (palms, a torii, a shipwreck, lantern beacons, bare rock) so "which one is that?" is answerable from the water. Every one has a landing pier.',
          '<b>Lanternhome</b> — the nearest island to the mainland, and the only place in the world you can build. See <i>Your Homestead</i>.',
          '<b>The Rialo Hub</b> — the far corner of the sea. A built island, not a found one.',
        ])}
        <p class="note">Land mounts dismount automatically at the waterline. You
        cannot attack, jump or raise a shield while swimming.</p>`),

      S('safe', 'Safe Zones', `
        <p>Four kinds of ground are sanctuaries. Nothing spawns in them, anything
        hunting you disengages at the edge, and monsters are physically pushed out
        if the world tries to put them inside.</p>
        ${ul([
          'The village plaza and its surroundings',
          'All six rest camps',
          'Your own house on Lanternhome, once the cabin is up',
          'Both lakes, plus a five-unit margin around them',
          'The whole Rialo Hub island',
        ])}
        <p>You also stop being a target entirely while you are <b>fishing</b> or
        <b>talking</b> to someone, wherever you are standing — an ambush during a
        cutscene you cannot act in is not difficulty, it is an accident.</p>
        <p class="note">Below Lv10 you also take reduced damage — 45% of the
        listed amount at Lv1, rising smoothly to the full amount by the awakening.
        An Origin has no burst, no escape and no heal, and the monsters were tuned
        for a class that starts with three abilities.</p>`),
    ],
  },

  {
    name: 'CORE SYSTEMS',
    sections: [
      S('combat', 'Combat', `
        <p>Attacks are camera-relative and auto-aim at the nearest valid target in
        front of you, so you aim by facing rather than by pixel-hunting. Each
        weapon type has its own swing: the axe is slower and wider than the sword,
        the cannon is the only basic attack with a blast radius, and daggers chain
        into a two-hit cross-slash.</p>
        ${ul([
          '<b>Roll</b> (Shift / right click) has invulnerability frames and costs stamina. Afloat it becomes a dive.',
          '<b>Shield</b> reduces damage while held and drains stamina. Sword Warriors only.',
          '<b>Out of combat you heal on your own.</b> You never have to walk home just to top off, and there is no potion tax on exploring.',
          '<b>Dying costs you nothing permanent.</b> No XP loss, no dropped items — you respawn in the village. The penalty is the walk back.',
        ])}
        ${call('do', 'READING A FIGHT', [
          'Every monster telegraphs. A charger rears back, a caster stops and glows, a boss winds up long enough that the tell is the point.',
          'Elites are the ones with a spinning gold ring and a ★ on the nameplate: 2.6× health, 1.5× damage, 2.5× XP. Do not open with them.',
          'Aggro ranges are deliberately short. Walking past something is usually allowed — you are not obliged to clear a field to cross it.',
          'Monster level rises with distance from the village AND with your own, so nowhere becomes trivial and nowhere becomes pointless.',
        ])}`),

      S('stats', 'Attributes', `
        <p><b>Z</b> opens your build. Every level pays <b>three points</b>, from Lv1
        onward, and there is <b>no respec</b> — at Lv30 you will have spent ninety
        of them and the hero you made is the hero you have.</p>
        <p>Each attribute owns exactly one obvious thing. That is on purpose: a
        wall of small percentages is a build system nobody can feel, and "I put ten
        into Agility" should have an answer you can watch happen.</p>
        ${kv([
          ['MIGHT', '+2.5% damage per point. It is folded into the same multiplier weapons, skills AND summons all read, so it never stops applying'],
          ['VITALITY', '+6 maximum HP per point'],
          ['AGILITY', '+1.2% attack speed and movement speed per point'],
          ['FOCUS', '+4 maximum stamina and +2% stamina regeneration per point'],
        ])}
        ${call('do', 'IF YOU ARE NOT SURE', [
          'Take Vitality first if you are learning the fights — dying less teaches you more than hitting harder.',
          'Might is the safest long-term pick because it reaches everything, including a Summoner\'s beasts and a Priest\'s smite.',
          'Focus is worth more than it looks if you swim, dive or roll a lot; stamina is what those all spend.',
        ])}`),

      S('classes', 'Classes & Skills', `
        <p>You do <b>not</b> pick a class when you make a character. Everyone starts
        as an <b>Origin</b>: one plain sword, and no skills at all. That is
        deliberate — the first ten levels are where you learn that swinging,
        dodging and reading a monster's tell is the actual game, and a hero handed
        three abilities up front has nothing to earn.</p>
        <p>At <b>Lv10</b> Elder Maple gives you <b>The Calling</b>, and
        <b>Grand Master Vell</b> — the owl on the shrine avenue — awakens you into
        one of six. This choice is <b>permanent</b>, so it asks twice.</p>
        ${kv([
          ['Warrior', 'Sword <i>or</i> Axe — you pick at the awakening. Sword is faster with a shield; the axe is slower, wider and hits far harder'],
          ['Archer', 'Bow · ranged, volleys, traps and one enormous snipe'],
          ['Mage', 'Staff · chain lightning, gravity wells, meteors'],
          ['Priest', 'Staff · heals, sanctuaries and pillars of light'],
          ['Assassin', 'Twin blades · huge melee area, stuns, and vanishing'],
          ['Summoner', 'Bazooka · the only basic attack with a blast radius. Calls beasts, walking robots, turrets and rocket barrages'],
        ])}
        <h4>THE SKILL TREE</h4>
        <p>Each class has its own tree of seven skills across three tiers, opening
        at <b>Lv10 / Lv16 / Lv24</b>. Open it with <b>K</b>.</p>
        ${call('do', 'THE TREE IN ONE LINE', [
          'Learning a skill is permanent and costs points.',
          'Slotting one is free — put any three learned skills on the bar and swap them whenever you like.',
          'So experimenting with a loadout never costs you the points you ground for.',
        ])}
        <p>You get <b>one skill point per level</b>. A skill can also reach level 5:
        each level is +22% power, −6% cooldown and longer buffs.</p>
        <p>No node in any tree is a hidden percentage. Every one of them changes
        something you can watch happen, and there is deliberately no "spend five
        here to open the next" — that only ever means everybody looks up the one
        correct path.</p>
        <h4>A NOTE ON SUMMONS</h4>
        <p>A Summoner's beasts, bots and turrets are <b>bodyguards, not a second
        player</b>. They hold a loose formation around you, they will only break
        off for something that has already come close to <i>you</i>, and a hard
        leash keeps them within a few units whatever they want to do. They have
        health and monsters can kill them, and there is a hard cap with the oldest
        culled first.</p>
        <p class="note">The first version let them roam and hunt on their own, which
        meant a Summoner could stand still, hold the button, and watch the map get
        cleared without them. That is not a class, it is an autoplayer.</p>`),

      S('slots', 'Heroes, Slots & Saving', `
        <p>You get <b>three character slots</b>. Choosing CONTINUE or PLAY ONLINE
        opens the hero select; a slot is either one of your characters or an empty
        plinth with <b>+ NEW HERO</b> on it.</p>
        <p>The level cap is <b>Lv30</b>. Auto-Battle (<b>B</b>) unlocks at
        <b>Lv10</b>, with the awakening — it walks to the nearest monster, fights
        it and moves on, and it is there so grinding materials is not a chore. It
        is <b>off by default</b> and it will not turn on before Lv10, because the
        first ten levels are the ones where you learn to fight.</p>
        ${call('dont', 'DELETE IS FOREVER', [
          'It asks twice, and then the character is gone.',
          'It removes the cloud copy too, so signing in elsewhere will not bring them back.',
        ])}
        <p><b>MAIN MENU</b> in the ☰ menu saves, disconnects and returns you to the
        title, where you can sign out or switch heroes.</p>`),

      S('rialohub', 'The Rialo Hub', `
        <p>Far out in the ocean, past the archipelago and roughly a hundred units
        from the village, there is an island somebody <i>built</i>: a ring plaza,
        a colonnade, the Rialo monument lit at its centre, and a banner board you
        can read from the water. The stone is deep blue-black with mint inlay —
        deliberately not Anavela's palette, because the place belongs to another
        world.</p>
        <p>Two people are there. <b>Baster</b> and <b>Dikzzy</b> will talk to you
        about what Rialo is actually for. And there is a second <b>Spider</b>, the
        black cat, sitting where she should not be able to have got to.</p>
        ${call('do', 'Getting there', [
          'Take a boat from the marina. It is too far to swim comfortably and that is the point — the Hub is a destination, not scenery.',
          'The whole island is a <b>safe zone</b>, so a low-level hero can stand around and read rather than being swarmed the moment they step off the pier.',
          'The camera lifts on its own as you approach the banner. If you would rather aim it yourself, the arrow keys suspend that for a few seconds.',
        ])}`),

      S('inv', 'Inventory, Hotbar & Levelling', `
        <p>Open the bag with <b>I</b>. Anything consumable can go on the hotbar.
        XP comes from kills, quests, gathering, fishing, cooking and forging — the
        game does not have a single "correct" way to level.</p>
        <p>Every level pays out: coins each time, tonics every third level, and an
        unowned cosmetic every fifth.</p>`),
    ],
  },

  {
    name: 'LIVELIHOODS',
    sections: [
      S('gather', 'Gathering & Crafting', `
        <p>Birch trees give <b>hardwood</b>, ore boulders give <b>iron ore</b> and
        <b>forge stones</b>. Three hits each, then they respawn on a timer.</p>
        <p>The <b>Craft</b> panel is filtered to your class, so you only ever see
        recipes you can actually use. The <b>Forge</b> takes a weapon from +1 to
        +9 using forge stones; higher levels can fail and cost the stones.</p>
        <p>Crafting is a <b>process you watch</b>, not a button that swaps items:
        the billet goes into the coals, you take three hammer blows to it with
        real sparks coming off the anvil, and the piece is quenched before it is
        yours. Your materials leave the bag when the billet goes in and the
        weapon lands on the last blow. <b>Hold anywhere to hurry it along.</b></p>`),

      S('farm', 'Farming & Cooking', `
        <p>Eight plots sit outside the plaza under the <b>FARM</b> sign. Two are
        free, the rest are bought. Plant a seed, wait through three growth stages,
        harvest the crop.</p>
        <p>Crops sell for more than seeds cost, and cooked food sells for more than
        raw crops — cook at any campfire or at the village hearth.</p>
        <p>Cooking is a <b>scene, not a click</b>. The fire is lit, each
        ingredient falls into the pot in turn and stains the broth toward the
        colour of the finished dish, it simmers while a spoon goes round, and the
        steam comes off it before you get anything. If the <b>Big Pot</b> life
        skill pays out, the card at the end tells you the pot stretched to two.
        <b>Hold anywhere to hurry it along.</b></p>`),

      S('fish', 'Fishing', `
        <p>Stand on a shore and press <b>F</b>. Cast, wait for the <b>!</b>, then
        strike. The rod tugs in rhythm when something is on; strike too early and
        it is gone.</p>
        <p><b>AFK fishing (G)</b> fishes for you at heavily reduced rarity. Every
        lake has a dock with a fishmonger who buys your catch on the spot.</p>
        <p class="note">You cannot be attacked while you are fishing, anywhere on
        the map. Standing on a wild shore watching a float is supposed to be the
        calm part of the game.</p>`),

      S('lifeskills', 'Life Skills', `
        <p><b>L</b>, or ☰ → LIFE SKILLS. Fishing, farming and cooking each level on
        their own experience and pay a point per level, spent on their own small
        tree.</p>
        <p>Nothing in here is a hidden number. Every node changes how the activity
        <i>plays</i>:</p>
        ${ul([
          '<b>Fishing</b> — a wider bite window so a late strike still lands, a second fish off one cast, and one three-point node that is the only thing in the game that unlocks <b>mythic fish</b>.',
          '<b>Farming</b> — an extra crop at harvest, the seed handed back, or a plant left standing so the plot keeps producing.',
          '<b>Cooking</b> — two portions out of one pot.',
        ])}
        <p>They level from doing the thing, so they come along on their own while
        you play. You never have to grind a life skill on purpose.</p>`),

      S('boats', 'Boats & Donut Boat', `
        <p>Two watercraft, both moored at the marina on the stretch of coast
        nearest the village (⛵ on the world map).</p>
        ${kv([
          ['Bobbin Dinghy', 'Free, from the start. Round-bottomed and beamy, oars in their locks, a lit bow lantern. Slow and forgiving.'],
          ['Donut Boat', '480c key from Pip\'s shop. A pink-glazed ring with sprinkles, a seat sunk in the hole and eight lamps round the rim. Fast, banks hard, drifts wide.'],
        ])}
        <p>Walk up and press <b>F</b> to board, <b>F</b> again to step off — you
        are put down on the nearest dry ground and the craft re-moors where it
        stopped. Nose into a beach and it bleeds off speed rather than sticking.</p>
        <p>Both hulls ride the real swell rather than the flat mean waterline, and
        sit far enough into it that they displace water instead of resting on top
        like a bath toy. They heel into a turn, porpoise over the crests, and throw
        foam off the stern and spray off the bow at speed. Every lamp on both
        craft lights at dusk and goes out at dawn.</p>
        <p class="note">There is a launch post at the head of every island pier, so
        you can call your boat to you rather than walking back across the map to
        wherever you left it.</p>`),

      S('house', 'Your Homestead', `
        <p>There is exactly one place in the world you may build, and it is
        already yours: <b>Lanternhome</b>, the small island off the south-east
        coast, marked <span style="color:#a8e06a">⌂</span> on the world map. The
        Lanternkeepers used it as a waystation; the foundation is still there,
        with a builder's post and a stack of timber nobody came back for.</p>
        <p>You do not buy land and you do not choose a design. The house is a
        <b>ladder of three tiers</b>, and you climb it one rung at a time — so
        every hero sees all three, in order, and the money always has somewhere
        to go.</p>
        ${kv([
          ['1 · Driftwood Cabin', '12 hardwood, 4 iron ore. One storey, green roof, a lamp by the door.'],
          ['2 · Anavela Cottage', '28 hardwood, 12 iron ore, 200c. Chimney, window boxes, picket fence, two path lamps, stepping stones down to the water.'],
          ['3 · Lanternkeeper\'s Villa', '45 hardwood, 22 iron ore, 600c. Two storeys, a balcony over the door, a stone wall with a gate, a well — and a beacon on the ridge that burns all night.'],
        ])}
        ${call('do', 'Getting there and getting it built', [
          'Take the <b>Bobbin Dinghy</b> from the marina, or just swim — Lanternhome is the nearest island to the mainland and the crossing is short.',
          'Chop <b>birch trees</b> for hardwood and mine <b>ore boulders</b> for iron ore. Three hits each, and they respawn elsewhere.',
          'Stand on the foundation and press <b>F</b>. The panel shows exactly what you are still short of.',
          'Once the cabin is up, <b>Teleport Home (T)</b> lands you beside the door from anywhere on the map — the 20-second cooldown is shared with Basecamp (Y).',
        ])}
        <p>A finished house is a <b>safe zone</b>: monsters are pushed out of it,
        nothing spawns inside, and standing near it heals you quickly — the same
        as a rest camp, except this one is on an island nobody else visits.</p>`),
    ],
  },

  {
    name: 'PROGRESSION',
    sections: [
      S('quests', 'Quests & The Story', `
        <p>Three layers, all running at once:</p>
        ${ul([
          '<b>The quest chain</b> — villagers with a <b>!</b>. Deliveries first, then mount hunts, then world bosses.',
          '<b>Repeatables</b> — kill, fish, forge, chest and delivery jobs you can take again.',
          '<b>The story of Anavela</b> — seven chapters about the Lanternkeepers. Each one unlocks from something you were going to do anyway (reach a level, swim, visit an island, raise your house), so it advances by playing rather than by scripted triggers. The card waits for you to close it, and every chapter pays a reward.',
        ])}
        <h4>THE TRACKER KNOWS WHERE</h4>
        <p>Every row in the quest tracker carries a <b>compass arrow and a
        distance</b> to whatever the next step actually is — the nearest live slime
        for "defeat 3 slimes", an unlooted chest for "open 2 chests", and the
        villager who asked once the work is done. <b>Click a row</b> to drop that
        target as a waypoint; a beacon chip then points at it from the HUD and
        clears itself when you arrive.</p>
        <p class="note">There is also a one-line hint under the tracker at all
        times. It always names the next thing worth doing. If you ever open the
        game and do not know what to do, that line is the answer.</p>`),

      S('daily', 'Daily, Play-time & GamePass', `
        <p>Three retention systems, all opened with <b>J</b>:</p>
        ${ul([
          '<b>30-day check-in</b> — one claim per day, escalating rewards, cosmetics at days 7/14/20/21/26/29 and the <b>Pebble mount at day 30</b>. Miss more than a day and the streak resets.',
          '<b>Play-time milestones</b> — at 5, 15, 30, 45 and 60 minutes of each session.',
          '<b>Daily quests</b> — three drawn from a pool of twelve, re-rolled at local midnight. Refreshing the page will not reroll them.',
        ])}
        <p><b>GamePass</b> is a season pass bought with gold you earned, not money.
        30 tiers, three reward rows:</p>
        ${kv([
          ['Free', 'Always claimable. Nobody is locked out of the track.'],
          ['Basic — 1,000c', '+10% XP'],
          ['Premium — 3,000c', '+25% XP, +15% luck, +10% coins'],
        ])}
        <p>Upgrading basic → premium only costs the difference, and every tier you
        have already passed is claimable retroactively. The track ends at
        <b>Aurora</b>, a mythic spirit-elk mount, on premium tier 30.</p>`),

      S('gacha', 'Wonder Capsules', `
        <p>The capsule machine on the third avenue. <b>100c</b> a pull, or
        <b>900c</b> for ten (you pay for nine). Six rarity tiers.</p>
        ${ul([
          'Pity: after 8 pulls with nothing epic or better, epic+ weight goes up until it breaks.',
          'Duplicates of a unique refund coins instead of clogging the bag.',
          'Weapons are rolled against <i>your</i> class, so a pull is never wasted on gear you cannot hold.',
          'Some pets, mounts and weapons only exist here — Glimmer, Nox, Seraphi, Blossom and Aurora among them.',
          '<b>📜 VIEW ALL PRIZES</b> shows the entire pool with per-tier odds before you spend anything.',
        ])}`),

      S('pets', 'Pets, Mounts & Wardrobe', `
        <p><b>13 pets</b> follow you and carry a passive perk — speed, damage,
        regeneration, attack speed, XP, armour, crit, stamina, pickup magnet or
        fishing luck. Ten drop from chests, bosses and quests; three are capsule
        exclusives.</p>
        <p><b>8 mounts</b>, each with its own speed and jump multiplier. Sprig is
        free from the start. Press <b>M</b> to summon.</p>
        <p><b>28 cosmetics</b> in the wardrobe (<b>O</b>): hats, back pieces and
        movement trails, plus a full re-edit of your hero's appearance and name at
        any time.</p>`),
    ],
  },

  {
    name: 'ECONOMY',
    sections: [
      S('gold', 'Gold & Rarity', `
        <p>Coins come from selling, quests, chests, levels and dailies. They go on
        seeds, farm plots, the two house upgrades, forge attempts, the Donut Boat
        key, the GamePass and the capsule machine.</p>
        <p>Six rarities run through everything — capsules, cosmetics, weapons and
        the reveal effects that go with them:</p>
        ${kv([
          ['Common', 'Materials and supplies'],
          ['Uncommon', 'Better supplies, basic cosmetics'],
          ['Rare', 'Good cosmetics, useful gear'],
          ['Epic', 'Starforged weapons, Pebble mount'],
          ['Legendary', 'Dragonfang weapons, Blossom mount'],
          ['Mythic', 'Celestium weapons, Aurora mount, Seraphi'],
        ])}
        <p>Duplicate uniques refund coins scaled to their rarity.</p>`),
    ],
  },

  {
    name: 'GAMEFI',
    sections: [
      S('token', 'Where Semesta Is Headed', `
        <p class="warn"><b>Nothing below is live.</b> Semesta today is a complete,
        free, offline single-player game with no wallet, no token and no on-chain
        anything. This section describes the plan, not the present. If a site or a
        message tells you to connect a wallet or buy a Semesta token today, it is
        not us.</p>
        <p>The intended path, in order:</p>
        ${ul([
          '<b>01 · Token Launchpad</b> — SEMESTA launches on the Semesta Launchpad with a total supply of 1,000,000,000.',
          '<b>02 · Hold to Play</b> — access gated on holding a minimum of 1,000 SEMESTA.',
          '<b>03 · Token Gacha</b> — the capsule machine accepts SEMESTA alongside in-game gold. Gold never stops working.',
          '<b>04 · Genesis NFT</b> — a free mint for players who were actually playing.',
        ])}
        <p><b>Multiplayer and the account login are already live</b> and are not
        part of the plan above: 🌐 PLAY ONLINE on the title screen joins a shared
        world with a shared clock, world chat and other players in it, and signing
        in with Google keeps your save in the cloud so it follows you between
        devices. They are free, they need no wallet, and they will stay that
        way.</p>`),
    ],
  },

  {
    name: 'HELP',
    sections: [
      S('faq', 'FAQ & Troubleshooting', `
        <h4>It runs badly / the camera stutters.</h4>
        <p>Open <b>GRAPHICS</b> — it is pinned to the right of this menu, and it is
        also in the in-game <b>☰</b> menu. Drop the preset to <b>LOW</b>. Render
        scale, shadows, particle effects, draw distance and world detail can each
        be overridden on their own if you would rather keep one of them high.
        World detail only takes effect on the next run; everything else is instant.</p>

        <h4>I am stuck inside a building.</h4>
        <p>Press <b>T</b> to teleport home and <b>Y</b> to teleport to the basecamp — your
        crops are at one and the shops, the forge and the gacha are at the other, which
        is why they are two buttons. Or press <b>N</b> and walk out along the road.
        The game also frees you automatically when a saved position turns out to be
        inside something.</p>

        <h4>Where did my save go?</h4>
        <p>By default it lives in this browser's local storage, so a different
        browser, a different device or clearing site data means a fresh start.
        <b>Sign in with Google</b> on the title screen and it is kept in the cloud
        as well — then it follows you anywhere you sign in. Local and cloud are
        reconciled when they disagree, and you are asked which to keep when the
        two are close enough that guessing would be rude.</p>

        <h4>I cannot find the chat button.</h4>
        <p>It only exists in a shared world. On a desktop it is the 💬 button and
        <b>Enter</b> also opens it; on a phone it is a round icon in the gap
        between the health plate and the minimap. While you are typing, the box
        pins itself to the <i>top</i> of the screen, because the on-screen keyboard
        covers the bottom third.</p>

        <h4>Something is standing between me and what I want to see.</h4>
        <p>The camera tilts. <b>↑</b> and <b>↓</b> on a desktop, or drag vertically
        on touch. It also lifts on its own when you walk up to something tall, and
        touching the tilt keys suspends that for a few seconds so it stops arguing
        with you.</p>

        <h4>Nothing happens when I press F.</h4>
        <p>You are not close enough, or something nearer has claimed the button.
        The prompt at the bottom of the screen always names what <b>F</b> and
        <b>R</b> will do right now — if it is blank, walk closer.</p>

        <h4>There is no sound.</h4>
        <p>Browsers will not start audio until you click. Click anywhere in the
        page once. All music and effects are synthesised live — there are no audio
        files to fail to load.</p>

        <h4>Can I play on my phone?</h4>
        <p>Yes. Touch controls appear automatically: a floating stick on the left,
        action buttons on the right, pinch to zoom. Bloom is switched off on touch
        devices whatever the preset says, because it costs more than it gives on a
        phone.</p>`),
    ],
  },
];

export const DOCS_CSS = `
#opening .docs .card {
  width: min(960px, 94vw); height: min(680px, 86vh); padding: 0;
  display: flex; flex-direction: column; text-align: left;
}
#opening .docs .dhead {
  display: flex; align-items: baseline; gap: 12px; flex-wrap: wrap;
  padding: 16px 20px 12px; border-bottom: 1px solid #46523c; flex: 0 0 auto;
}
#opening .docs .dhead h4 {
  font-family: var(--font-display, inherit); font-size: 13px; letter-spacing: 4px;
  color: var(--gold, #d8b866); margin: 0;
}
#opening .docs .dhead span { font-size: 9px; letter-spacing: 1px; color: #8d9a80; }
#opening .docs .dbody { display: flex; flex: 1 1 auto; min-height: 0; }
#opening .docs .dnav {
  flex: 0 0 194px; overflow-y: auto; padding: 12px 8px 20px;
  border-right: 1px solid #2e3828; background: rgba(8,11,7,0.45);
}
#opening .docs .dnav .cat {
  font-size: 8px; letter-spacing: 3px; color: #7d8a70; margin: 14px 10px 5px;
}
#opening .docs .dnav .cat:first-child { margin-top: 2px; }
#opening .docs .dnav a {
  display: block; font-size: 10px; color: #c2cbb0; padding: 5px 10px;
  cursor: pointer; border-left: 2px solid transparent; text-decoration: none;
}
#opening .docs .dnav a:hover { color: #ffe9b0; background: rgba(216,184,102,0.07); }
#opening .docs .dnav a.on {
  color: #ffe9b0; border-left-color: var(--gold, #d8b866);
  background: rgba(216,184,102,0.12);
}
#opening .docs .dmain {
  flex: 1 1 auto; overflow-y: auto; padding: 6px 24px 40px;
}
#opening .docs .sec { padding-top: 20px; scroll-margin-top: 8px; }
#opening .docs .sec > h3 {
  font-family: var(--font-display, inherit); font-size: 11px; letter-spacing: 3px;
  color: var(--gold, #d8b866); margin: 0 0 10px;
  padding-bottom: 7px; border-bottom: 1px solid #333d2c;
}
#opening .docs p { font-size: 10px; line-height: 1.95; color: #ccd4bd; margin: 0 0 10px; }
#opening .docs p.note {
  color: #9fb08c; border-left: 2px solid #4a5a3c; padding-left: 10px;
}
#opening .docs p.warn {
  color: #ffd9c2; background: rgba(180,80,50,0.14);
  box-shadow: inset 0 0 0 1px rgba(220,120,80,0.35); padding: 10px 12px;
}
#opening .docs b { color: #f0e8cc; }
#opening .docs i { color: #a8b596; font-style: normal; opacity: 0.9; }
#opening .docs code {
  font-family: ui-monospace, monospace; font-size: 9px; color: #ffe9b0;
  background: rgba(0,0,0,0.35); padding: 1px 4px;
}
#opening .docs h4 {
  font-size: 10px; letter-spacing: 1px; color: #e8dcb8; margin: 14px 0 6px;
}
#opening .docs ul { margin: 0 0 12px; padding-left: 16px; }
#opening .docs li { font-size: 10px; line-height: 1.85; color: #ccd4bd; margin-bottom: 3px; }
#opening .docs .cal { padding: 11px 14px 6px; margin: 0 0 12px; }
#opening .docs .cal h4 { margin: 0 0 6px; font-size: 9px; letter-spacing: 2px; }
#opening .docs .cal ul { margin-bottom: 6px; }
#opening .docs .cal.do {
  background: rgba(90,140,70,0.13); box-shadow: inset 0 0 0 1px rgba(140,200,110,0.3);
}
#opening .docs .cal.do h4 { color: #b6e08a; }
#opening .docs .cal.dont {
  background: rgba(150,80,60,0.13); box-shadow: inset 0 0 0 1px rgba(220,130,100,0.28);
}
#opening .docs .cal.dont h4 { color: #f0b09a; }
#opening .docs table.kv { width: 100%; border-collapse: collapse; margin: 0 0 12px; }
#opening .docs table.kv th, #opening .docs table.kv td {
  font-size: 10px; text-align: left; padding: 5px 8px; vertical-align: top;
  border-bottom: 1px solid #2a3324;
}
#opening .docs table.kv th { color: #e8dcb8; font-weight: normal; width: 34%; }
#opening .docs table.kv td { color: #ccd4bd; line-height: 1.7; }
#opening .docs .dfoot {
  flex: 0 0 auto; padding: 10px 20px; border-top: 1px solid #46523c;
  display: flex; justify-content: space-between; align-items: center; gap: 10px;
}
#opening .docs .dfoot .tag { font-size: 8px; letter-spacing: 2px; color: #7d8a70; }
#opening .docs .dfoot button { margin: 0; }
@media (max-width: 720px) {
  #opening .docs .card { width: 96vw; height: 90vh; }
  #opening .docs .dbody { flex-direction: column; }
  #opening .docs .dnav {
    flex: 0 0 auto; max-height: 116px; border-right: 0;
    border-bottom: 1px solid #2e3828; display: flex; flex-wrap: wrap; gap: 2px;
  }
  #opening .docs .dnav .cat { width: 100%; margin: 6px 8px 2px; }
  #opening .docs .dnav a { border-left: 0; border-bottom: 2px solid transparent; padding: 4px 8px; }
  #opening .docs .dnav a.on { border-left: 0; border-bottom-color: var(--gold, #d8b866); }
  #opening .docs .dmain { padding: 4px 14px 30px; }
}
`;

/** The whole guide as markup: a sidebar built from the same data as the body. */
export function docsInner() {
  const nav = CATEGORIES.map((c) => `
    <div class="cat">${c.name}</div>
    ${c.sections.map((s) => `<a data-go="${s.id}">${s.title}</a>`).join('')}`).join('');
  const main = CATEGORIES.map((c) => c.sections.map((s) => `
    <section class="sec" id="doc-${s.id}">
      <h3>${s.title}</h3>
      ${s.body}
    </section>`).join('')).join('');
  return `<div class="card">
    <div class="dhead">
      <h4>SEMESTA GUIDE</h4>
      <span>How to play Anavela Universe — controls, systems, economy, and what is coming.</span>
    </div>
    <div class="dbody">
      <nav class="dnav">${nav}</nav>
      <div class="dmain">${main}</div>
    </div>
    <div class="dfoot">
      <span class="tag">◆ BUILD FOR RIALO ◆</span>
      <button class="closebtn">BACK</button>
    </div>
  </div>`;
}

/**
 * Wire the sidebar: clicking scrolls, and scrolling highlights. Called once
 * after the markup is in the DOM.
 */
export function wireDocs(rootEl) {
  const main = rootEl.querySelector('.dmain');
  const links = [...rootEl.querySelectorAll('.dnav a')];
  const secs = links.map((a) => rootEl.querySelector(`#doc-${a.dataset.go}`));
  // Measure against the RECTS, not offsetTop. .dmain is not the offsetParent of
  // its own sections, so offsetTop was measured from somewhere further up the
  // tree and every jump landed in the wrong place — or, as here, nowhere at all.
  const offsetIn = (el) =>
    el.getBoundingClientRect().top - main.getBoundingClientRect().top + main.scrollTop;
  links.forEach((a, i) => {
    a.addEventListener('click', () => {
      // scroll the PANE, not the page — the modal is its own scroll container
      // INSTANT, deliberately. Both scrollTo({behavior:'smooth'}) and the CSS
      // scroll-behavior property are silently inert whenever the tab is
      // throttled — measured here as a jump to 800 landing at 0 — and a sidebar
      // link that sometimes does nothing is worse than one that never eases.
      main.scrollTop = Math.max(0, offsetIn(secs[i]) - 6);
      // highlight straight away rather than waiting for the scroll event, which
      // is passive and can arrive a frame or two late (or not at all when the
      // tab is throttled)
      links.forEach((x, j) => x.classList.toggle('on', j === i));
    });
  });
  const mark = () => {
    let best = 0;
    for (let i = 0; i < secs.length; i++) {
      if (offsetIn(secs[i]) - main.scrollTop <= 60) best = i;
    }
    links.forEach((a, i) => a.classList.toggle('on', i === best));
  };
  main.addEventListener('scroll', mark, { passive: true });
  mark();
  return { reset: () => { main.scrollTop = 0; mark(); } };
}
