// A QR ENCODER, written out because we cannot ship one.
//
// The house rule for this project is that nothing is an asset file and nothing
// is fetched at runtime — every texture, icon and sound is generated by code as
// the game loads. A QR code is no different: no image, no CDN library, no API
// that renders one for us. So this is a real encoder.
//
// Deliberately narrow. It does byte mode at error-correction level M, picks the
// smallest version that fits, and applies all eight masks to choose the one with
// the lowest penalty, exactly as the spec requires. That is everything a URL
// needs and nothing more — no kanji mode, no structured append, no ECI.
//
// Reference: ISO/IEC 18004. The tables below are from the standard.

// --- Galois field GF(256), primitive polynomial 0x11D -----------------------
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();
const mul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

/**
 * Reed-Solomon generator polynomial of `degree`, LEADING COEFFICIENT FIRST.
 *
 * The loop below builds it the other way up — poly[0] ends as the constant
 * term — and `rsEncode` reads gen[0] as the leading 1. So the two disagreed by
 * a reversal, every parity byte came out wrong, and a scanner computing the
 * syndromes of the finished block found 25 of 26 non-zero and threw the symbol
 * away. Checked against the published QR test vector: the degree-10 generator
 * must be 01 d8 c2 9f 6f c7 5e 5f 71 9d c1, and it was arriving as exactly that
 * backwards.
 */
function rsPoly(degree) {
  let poly = [1];
  for (let i = 0; i < degree; i++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let j = 0; j < poly.length; j++) {
      next[j] ^= mul(poly[j], EXP[i]);
      next[j + 1] ^= poly[j];
    }
    poly = next;
  }
  return poly.reverse();
}

/** The EC codewords for one data block. */
function rsEncode(data, ecLen) {
  const gen = rsPoly(ecLen);
  const res = new Array(ecLen).fill(0);
  for (const byte of data) {
    const factor = byte ^ res[0];
    res.shift();
    res.push(0);
    for (let i = 0; i < ecLen; i++) res[i] ^= mul(gen[i + 1], factor);
  }
  return res;
}

// --- version tables, error-correction level M -------------------------------
// [total codewords, EC codewords per block, group1 blocks, group2 blocks]
const VERSIONS_M = {
  1: [26, 10, 1, 0], 2: [44, 16, 1, 0], 3: [70, 26, 1, 0], 4: [100, 18, 2, 0],
  5: [134, 24, 2, 0], 6: [172, 16, 4, 0], 7: [196, 18, 4, 0], 8: [242, 22, 2, 2],
  9: [292, 22, 3, 2], 10: [346, 26, 4, 1],
};
/** Alignment-pattern centres per version. */
const ALIGN = {
  1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30],
  6: [6, 34], 7: [6, 22, 38], 8: [6, 24, 42], 9: [6, 26, 46], 10: [6, 28, 50],
};

/** Data capacity in bytes for byte mode at level M. */
function capacity(version) {
  const [total, ecPerBlock, g1, g2] = VERSIONS_M[version];
  const blocks = g1 + g2;
  const dataCodewords = total - ecPerBlock * blocks;
  const lenBits = version < 10 ? 8 : 16;
  return dataCodewords - 2 - Math.ceil(lenBits / 8);   // mode nibble + length
}

/**
 * Encode `text` and return a square matrix of 0/1, size (17 + 4*version).
 * Throws if the string is longer than this encoder's largest version.
 */
export function qrMatrix(text) {
  const bytes = new TextEncoder().encode(text);
  let version = 0;
  for (let v = 1; v <= 10; v++) {
    if (bytes.length <= capacity(v)) { version = v; break; }
  }
  if (!version) throw new Error(`QR: ${bytes.length} bytes is too long`);

  const [total, ecPerBlock, g1, g2] = VERSIONS_M[version];
  const blocks = g1 + g2;
  const dataCodewords = total - ecPerBlock * blocks;
  const size = 17 + version * 4;

  // ---- bit stream: mode (0100) + length + payload -------------------------
  const bits = [];
  const push = (val, len) => { for (let i = len - 1; i >= 0; i--) bits.push((val >> i) & 1); };
  push(0b0100, 4);
  push(bytes.length, version < 10 ? 8 : 16);
  for (const b of bytes) push(b, 8);
  // terminator, then pad to a byte boundary
  for (let i = 0; i < 4 && bits.length < dataCodewords * 8; i++) bits.push(0);
  while (bits.length % 8) bits.push(0);
  // pad bytes alternate 0xEC / 0x11 until the block is full
  const padBytes = [0xec, 0x11];
  let pad = 0;
  while (bits.length < dataCodewords * 8) push(padBytes[pad++ % 2], 8);

  const codewords = [];
  for (let i = 0; i < bits.length; i += 8) {
    let v = 0;
    for (let j = 0; j < 8; j++) v = (v << 1) | bits[i + j];
    codewords.push(v);
  }

  // ---- split into blocks, compute EC, then interleave ---------------------
  const shortLen = Math.floor(dataCodewords / blocks);
  const dataBlocks = [];
  const ecBlocks = [];
  let at = 0;
  for (let b = 0; b < blocks; b++) {
    const len = shortLen + (b >= g1 + g2 - g2 && g2 ? 1 : 0);
    const block = codewords.slice(at, at + len);
    at += len;
    dataBlocks.push(block);
    ecBlocks.push(rsEncode(block, ecPerBlock));
  }
  const finalBytes = [];
  const maxData = Math.max(...dataBlocks.map((b) => b.length));
  for (let i = 0; i < maxData; i++) {
    for (const b of dataBlocks) if (i < b.length) finalBytes.push(b[i]);
  }
  for (let i = 0; i < ecPerBlock; i++) {
    for (const b of ecBlocks) finalBytes.push(b[i]);
  }

  // ---- lay out the modules ------------------------------------------------
  const m = Array.from({ length: size }, () => new Int8Array(size).fill(-1));
  const set = (r, c, v) => { if (r >= 0 && c >= 0 && r < size && c < size) m[r][c] = v; };

  // finder patterns + separators
  const finder = (r0, c0) => {
    for (let r = -1; r <= 7; r++) {
      for (let c = -1; c <= 7; c++) {
        const inner = r >= 0 && r <= 6 && c >= 0 && c <= 6;
        const on = inner && (r === 0 || r === 6 || c === 0 || c === 6
          || (r >= 2 && r <= 4 && c >= 2 && c <= 4));
        set(r0 + r, c0 + c, on ? 1 : 0);
      }
    }
  };
  finder(0, 0); finder(0, size - 7); finder(size - 7, 0);

  // timing patterns
  for (let i = 8; i < size - 8; i++) {
    if (m[6][i] === -1) m[6][i] = i % 2 === 0 ? 1 : 0;
    if (m[i][6] === -1) m[i][6] = i % 2 === 0 ? 1 : 0;
  }

  // alignment patterns
  const centres = ALIGN[version];
  for (const r of centres) {
    for (const c of centres) {
      if (m[r][c] !== -1) continue;                 // skip the finder corners
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          const on = Math.max(Math.abs(dr), Math.abs(dc)) !== 1;
          set(r + dr, c + dc, on ? 1 : 0);
        }
      }
    }
  }

  // the dark module, always set
  m[size - 8][8] = 1;

  // reserve the format-information areas so data does not land in them
  const reserved = [];
  for (let i = 0; i < 9; i++) { reserved.push([8, i], [i, 8]); }
  for (let i = 0; i < 8; i++) { reserved.push([8, size - 1 - i], [size - 1 - i, 8]); }
  for (const [r, c] of reserved) if (m[r][c] === -1) m[r][c] = 0;

  // ---- zigzag the data in -------------------------------------------------
  let bitIndex = 0;
  const nextBit = () => {
    const byte = finalBytes[bitIndex >> 3];
    const bit = byte === undefined ? 0 : (byte >> (7 - (bitIndex & 7))) & 1;
    bitIndex++;
    return bit;
  };
  let upward = true;
  for (let col = size - 1; col > 0; col -= 2) {
    if (col === 6) col--;                           // the vertical timing column
    for (let i = 0; i < size; i++) {
      const row = upward ? size - 1 - i : i;
      for (const c of [col, col - 1]) {
        if (m[row][c] !== -1) continue;
        m[row][c] = nextBit();
      }
    }
    upward = !upward;
  }

  // ---- masking: try all eight, keep the least penalised -------------------
  const MASKS = [
    (r, c) => (r + c) % 2 === 0,
    (r) => r % 2 === 0,
    (r, c) => c % 3 === 0,
    (r, c) => (r + c) % 3 === 0,
    (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
    (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
    (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
    (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
  ];
  const isReserved = (r, c) =>
    reserved.some(([rr, cc]) => rr === r && cc === c)
    || (r === 6 || c === 6)
    || (r < 9 && c < 9) || (r < 9 && c >= size - 8) || (r >= size - 8 && c < 9)
    || centres.some((ar) => centres.some((ac) =>
      m[ar] && Math.abs(r - ar) <= 2 && Math.abs(c - ac) <= 2 && !(ar < 9 && ac < 9)
      && !(ar < 9 && ac >= size - 8) && !(ar >= size - 8 && ac < 9)));

  const penalty = (grid) => {
    let p = 0;
    // rule 1: runs of five or more
    for (let i = 0; i < size; i++) {
      for (const line of [grid[i], grid.map((row) => row[i])]) {
        let run = 1;
        for (let j = 1; j < size; j++) {
          if (line[j] === line[j - 1]) run++;
          else { if (run >= 5) p += run - 2; run = 1; }
        }
        if (run >= 5) p += run - 2;
      }
    }
    // rule 2: 2x2 blocks of one colour
    for (let r = 0; r < size - 1; r++) {
      for (let c = 0; c < size - 1; c++) {
        const v = grid[r][c];
        if (v === grid[r][c + 1] && v === grid[r + 1][c] && v === grid[r + 1][c + 1]) p += 3;
      }
    }
    // rule 4: deviation from a 50/50 light/dark split
    let dark = 0;
    for (let r = 0; r < size; r++) for (let c = 0; c < size; c++) dark += grid[r][c];
    const pct = (dark * 100) / (size * size);
    p += Math.floor(Math.abs(pct - 50) / 5) * 10;
    return p;
  };

  // format info: level M is 00, then the 3-bit mask, BCH(15,5) + 0x5412
  const formatBits = (maskId) => {
    const data = (0b00 << 3) | maskId;
    let rem = data << 10;
    for (let i = 14; i >= 10; i--) if ((rem >> i) & 1) rem ^= 0b10100110111 << (i - 10);
    return ((data << 10) | rem) ^ 0b101010000010010;
  };

  let best = null;
  for (let maskId = 0; maskId < 8; maskId++) {
    const g = m.map((row, r) => Array.from(row, (v, c) =>
      (isReserved(r, c) ? v : (MASKS[maskId](r, c) ? v ^ 1 : v))));
    // write this mask's format bits before scoring, so the score is honest
    // FORMAT INFORMATION — and this whole block was TRANSPOSED.
    //
    // Every cell was written with its row and column the wrong way round, so
    // the fifteen format bits landed in the mirror image of where they belong.
    // The format is the first thing a scanner reads: it carries the error level
    // and, critically, WHICH MASK was applied. Get it wrong and the scanner
    // cannot un-mask the data, so it does not read a corrupt payload — it does
    // not recognise the symbol as a QR code at all. Which is exactly what was
    // reported: not misread, not detected.
    //
    // It survived my own round-trip test because the decoder I wrote to check
    // it read the bits back out of the same transposed cells and agreed with
    // itself. Writing both halves of a test is how a shared mistake cancels.
    //
    // The correct placement, in [row][col]:
    //   copy 1  bits 0-5 -> (i, 8) | bit 6 -> (7, 8) | bit 7 -> (8, 8)
    //           bit 8 -> (8, 7)    | bits 9-14 -> (8, 14 - i)
    //   copy 2  bits 0-7 -> (8, size-1-i)  | bits 8-14 -> (size-15+i, 8)
    const fmt = formatBits(maskId);
    for (let i = 0; i < 15; i++) {
      const bit = (fmt >> i) & 1;
      // copy 1, around the top-left finder
      if (i < 6) g[i][8] = bit;
      else if (i === 6) g[7][8] = bit;
      else if (i === 7) g[8][8] = bit;
      else if (i === 8) g[8][7] = bit;
      else g[8][14 - i] = bit;
      // copy 2, split between the top-right and bottom-left finders
      if (i < 8) g[8][size - 1 - i] = bit;
      else g[size - 15 + i][8] = bit;
    }
    g[size - 8][8] = 1;                       // the dark module, always set
    const score = penalty(g);
    if (!best || score < best.score) best = { score, grid: g };
  }
  return best.grid;
}

/**
 * Paint a QR for `text` onto a canvas, one module per `scale` pixels, with a
 * proper quiet zone (4 modules) — scanners genuinely need it, and a QR bled to
 * the edge of a dark panel is the classic reason one will not read.
 */
export function makeQrCanvas(text, { scale = 4, dark = '#12160f', light = '#ffffff', quiet = 4 } = {}) {
  const grid = qrMatrix(text);
  const n = grid.length;
  const px = (n + quiet * 2) * scale;
  const c = document.createElement('canvas');
  c.width = px; c.height = px;
  const ctx = c.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.fillStyle = light;
  ctx.fillRect(0, 0, px, px);
  ctx.fillStyle = dark;
  for (let r = 0; r < n; r++) {
    for (let col = 0; col < n; col++) {
      if (grid[r][col]) ctx.fillRect((col + quiet) * scale, (r + quiet) * scale, scale, scale);
    }
  }
  return c;
}
